name: Lint
on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      # TODO: add caching of Pipfile.lock
      - name: Install dependencies
        run: pipenv install --dev --deploy
      - name: Run mypy
        run: pipenv run mypy .
